name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_training:
    +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      marketing:
        +schema: marketing