version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
  - name: ecomm
    database: raw
    tables:
      - name: customers
        description: "Customer master data with communication addresses."
        columns:
          - name: id
            description: '{{ doc("customer_id")}}'
      - name: orders
        identifier: orders_us
        description: "Order data which are given in US."
      - name: deliveries
        description: "Delivery data with status."
