version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses

  - name: ecomm
    database: raw
    tables:
      - name: orders
        identifier: orders_us
        description: All orders in ecomm
      - name: customers
        description: '{{ doc("customers") }}'
        columns: 
          - name: customer_id
            description: '{{ doc("customer_id") }}'
      - name: deliveries
        description: All deliveries in ecomm
