version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
      - name: stg_ecomm__orders
      - name: stg_ecomm__customers
  - name: ecomm  
    database: raw
    tables: 
      - name: customers
        columns:
        - name: customer_id
          tests:
            - unique
            - not_null      
      - name: orders
        columns:
        - name: order_id
          tests:
            - unique
            - not_null      
        - name: delivery_time_from_collection
          tests:
            - greater_than_zero            
      - name: deliveries
