version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: customers
        description: This record represents customers.
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'
      - name: orders
        identifier: orders_us 
        description: This record represents orders in the US.
      - name: deliveries
        description: This record represents an order delivery.