version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
  
  - name: ecomm
    database: raw
    schema: ecomm
    tables:
      - name: orders
        identifier: orders_us
        description: This table holds the whole information about orders
      - name: customers
        description: This table hols the whole information about customers
        columns:
          - name: customer_id
            description: "{{ doc('customer_id')}}"
      - name: deliveries
