version : 2

sources:
  - name : ecomm
    database : raw
    tables :
      - name : customers
        description : each record represents a customer 
        columns :
          - name : id 
            description : '{{ doc("customer_id") }}'
      - name : orders
        identifier : orders_us
        description : each record represents a order information
      - name : deliveries
        description : each record represents a order delivery