version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
        columns:
          - name: survey_date
          - name: satisfaction_score
  - name: ecomm
    database: raw
    tables:
      - name: orders
        identifier: orders_us
        description: All orders in ecomm raw source
      - name: customers
        description: This table contains all customers in ecomm raw source
        columns: 
          - name: customer_id
            description: '{{ doc("customer_id") }}'
      - name: deliveries
        description: All deliveries in ecomm
  - name: movies
    database: raw
    tables:
      - name: ratings
        description: All ratings in ecomm