version: 2

sources:
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses
  - name: ecomm
    database: raw
    tables:
      - name: customers
        columns:
          - name: id
      - name: orders
        identifier: orders_us
      - name: deliveries
    