version : 2

sources:
  - name : ecomm
    database : raw
    tables :
      - name : customers
        description : each record represents a customer 
        columns :
          - name : id 
            description : '{{ doc("customer_id") }}'
      - name : orders
        identifier : orders_us
        description : each record represents a order information
      - name : deliveries
        description : each record represents a order delivery


  - name : sheets
    database : raw
    tables : 
      - name : customer_survey_responses
        description : each record represents a survey response from customer
  
  - name : movies
    database : raw
    tables :
      - name : ratings
        description : each record represents a movie ratings by user
